// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/receiver/proto/message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HandshakeReq struct {
	RouterId             string   `protobuf:"bytes,1,opt,name=routerId,proto3" json:"routerId,omitempty"`
	AuthKey              string   `protobuf:"bytes,2,opt,name=authKey,proto3" json:"authKey,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeReq) Reset()         { *m = HandshakeReq{} }
func (m *HandshakeReq) String() string { return proto.CompactTextString(m) }
func (*HandshakeReq) ProtoMessage()    {}
func (*HandshakeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3aacdbb230774d, []int{0}
}
func (m *HandshakeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeReq.Unmarshal(m, b)
}
func (m *HandshakeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeReq.Marshal(b, m, deterministic)
}
func (m *HandshakeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeReq.Merge(m, src)
}
func (m *HandshakeReq) XXX_Size() int {
	return xxx_messageInfo_HandshakeReq.Size(m)
}
func (m *HandshakeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeReq.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeReq proto.InternalMessageInfo

func (m *HandshakeReq) GetRouterId() string {
	if m != nil {
		return m.RouterId
	}
	return ""
}

func (m *HandshakeReq) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

func (m *HandshakeReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type HandshakeRes struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeRes) Reset()         { *m = HandshakeRes{} }
func (m *HandshakeRes) String() string { return proto.CompactTextString(m) }
func (*HandshakeRes) ProtoMessage()    {}
func (*HandshakeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3aacdbb230774d, []int{1}
}
func (m *HandshakeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeRes.Unmarshal(m, b)
}
func (m *HandshakeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeRes.Marshal(b, m, deterministic)
}
func (m *HandshakeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeRes.Merge(m, src)
}
func (m *HandshakeRes) XXX_Size() int {
	return xxx_messageInfo_HandshakeRes.Size(m)
}
func (m *HandshakeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeRes.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeRes proto.InternalMessageInfo

func (m *HandshakeRes) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type HeartbeatReq struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatReq) Reset()         { *m = HeartbeatReq{} }
func (m *HeartbeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartbeatReq) ProtoMessage()    {}
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3aacdbb230774d, []int{2}
}
func (m *HeartbeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatReq.Unmarshal(m, b)
}
func (m *HeartbeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatReq.Marshal(b, m, deterministic)
}
func (m *HeartbeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatReq.Merge(m, src)
}
func (m *HeartbeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartbeatReq.Size(m)
}
func (m *HeartbeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatReq proto.InternalMessageInfo

func (m *HeartbeatReq) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HeartbeatRes struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRes) Reset()         { *m = HeartbeatRes{} }
func (m *HeartbeatRes) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRes) ProtoMessage()    {}
func (*HeartbeatRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3aacdbb230774d, []int{3}
}
func (m *HeartbeatRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRes.Unmarshal(m, b)
}
func (m *HeartbeatRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRes.Marshal(b, m, deterministic)
}
func (m *HeartbeatRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRes.Merge(m, src)
}
func (m *HeartbeatRes) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRes.Size(m)
}
func (m *HeartbeatRes) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRes.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRes proto.InternalMessageInfo

func (m *HeartbeatRes) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HeartbeatRes) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type MessageReq struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReq) Reset()         { *m = MessageReq{} }
func (m *MessageReq) String() string { return proto.CompactTextString(m) }
func (*MessageReq) ProtoMessage()    {}
func (*MessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3aacdbb230774d, []int{4}
}
func (m *MessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReq.Unmarshal(m, b)
}
func (m *MessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReq.Marshal(b, m, deterministic)
}
func (m *MessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReq.Merge(m, src)
}
func (m *MessageReq) XXX_Size() int {
	return xxx_messageInfo_MessageReq.Size(m)
}
func (m *MessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReq proto.InternalMessageInfo

func (m *MessageReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *MessageReq) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type MessageRes struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRes) Reset()         { *m = MessageRes{} }
func (m *MessageRes) String() string { return proto.CompactTextString(m) }
func (*MessageRes) ProtoMessage()    {}
func (*MessageRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3aacdbb230774d, []int{5}
}
func (m *MessageRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRes.Unmarshal(m, b)
}
func (m *MessageRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRes.Marshal(b, m, deterministic)
}
func (m *MessageRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRes.Merge(m, src)
}
func (m *MessageRes) XXX_Size() int {
	return xxx_messageInfo_MessageRes.Size(m)
}
func (m *MessageRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRes.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRes proto.InternalMessageInfo

func (m *MessageRes) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MessageRes) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*HandshakeReq)(nil), "HandshakeReq")
	proto.RegisterType((*HandshakeRes)(nil), "HandshakeRes")
	proto.RegisterType((*HeartbeatReq)(nil), "HeartbeatReq")
	proto.RegisterType((*HeartbeatRes)(nil), "HeartbeatRes")
	proto.RegisterType((*MessageReq)(nil), "MessageReq")
	proto.RegisterType((*MessageRes)(nil), "MessageRes")
}

func init() {
	proto.RegisterFile("proto/receiver/proto/message.proto", fileDescriptor_ac3aacdbb230774d)
}

var fileDescriptor_ac3aacdbb230774d = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4a, 0x4d, 0x4e, 0xcd, 0x2c, 0x4b, 0x2d, 0xd2, 0x87, 0x70, 0x73, 0x53, 0x8b,
	0x8b, 0x13, 0xd3, 0x53, 0xf5, 0xc0, 0x3c, 0xa5, 0x38, 0x2e, 0x1e, 0x8f, 0xc4, 0xbc, 0x94, 0xe2,
	0x8c, 0xc4, 0xec, 0xd4, 0xa0, 0xd4, 0x42, 0x21, 0x29, 0x2e, 0x8e, 0xa2, 0xfc, 0xd2, 0x92, 0xd4,
	0x22, 0xcf, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x48, 0x82, 0x8b, 0x3d,
	0xb1, 0xb4, 0x24, 0xc3, 0x3b, 0xb5, 0x52, 0x82, 0x09, 0x2c, 0x05, 0xe3, 0x82, 0x64, 0x8a, 0x53,
	0x8b, 0xca, 0x32, 0x93, 0x53, 0x25, 0x98, 0x21, 0x32, 0x50, 0xae, 0x92, 0x12, 0x8a, 0xf9, 0xc5,
	0x42, 0x42, 0x5c, 0x2c, 0xc9, 0xf9, 0x29, 0xa9, 0x60, 0xb3, 0x79, 0x83, 0xc0, 0x6c, 0x25, 0x0d,
	0x2e, 0x1e, 0x8f, 0xd4, 0xc4, 0xa2, 0x92, 0xa4, 0xd4, 0xc4, 0x12, 0x90, 0x1b, 0x24, 0xb8, 0xd8,
	0x0b, 0x12, 0x2b, 0x73, 0xf2, 0x13, 0x21, 0x4e, 0xe0, 0x09, 0x82, 0x71, 0x95, 0x6c, 0x50, 0x54,
	0x62, 0x35, 0x0d, 0x59, 0x37, 0x13, 0xaa, 0x6e, 0x07, 0x2e, 0x2e, 0x5f, 0x88, 0xe7, 0xa1, 0xb6,
	0xc0, 0xdc, 0xcc, 0x88, 0xe2, 0x66, 0x3c, 0x26, 0x58, 0x21, 0x99, 0x40, 0xa2, 0xed, 0x4e, 0xc2,
	0x51, 0x82, 0xe8, 0xf1, 0x91, 0x94, 0xc4, 0x06, 0x16, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x4a, 0x86, 0xc3, 0x73, 0xab, 0x01, 0x00, 0x00,
}
